dist: trusty

language: ruby

sudo: required

before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

cache: bundler

rvm:
 - 2.6.3

env:
 - DB=pgsql

services:
 - postgresql

test:
  adapter: postgresql
  database: transmogram_test

addons:
  chrome: stable
  postgresql: '11.3'

before_script:
  - cp config/database.yml.travis config/database.yml

# uncomment and edit the following line if your project needs to run something other than `rake`:
script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec

deploy:
  provider: heroku
  api_key:
    secure: "e1f1a63d-bf5c-410c-b349-5ef03dc80d3d"
  app: handsomecake-development-tmog

notifications:
  slack: yadadya:dw75tQmpnDHUXVCabdc2RABS