dist: trusty

language: ruby

sudo: required

before_install:
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

cache: bundler

rvm:
 - 2.6.3

env:
 - DB=pgsql

services:
 - postgresql

test:
  adapter: postgresql
  database: transmogram_test

addons:
  chrome: stable
  postgresql: "10"

# uncomment and edit the following line if your project needs to run something other than `rake`:
# script:
# - bundle exec rspec spec

before_script:
 - cp config/database.yml.travis config/database.yml
 - psql -c 'create database transmogram_test;' -U postgres
 - bundle update
 - bundle exec rake db:test:prepare
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sleep 3

deploy:
  provider: heroku
  api_key:
    secure: "e1f1a63d-bf5c-410c-b349-5ef03dc80d3d"
  app: handsomecake-development-tmog

notifications:
  slack: yadadya:dw75tQmpnDHUXVCabdc2RABS